spring:
    jpa:
        hibernate:
            ddl-auto: update
    show-sql: true
    datasource:
        url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: password
        driverClassName: org.h2.Driver
        jpa:
            spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    mail:
        default-encoding: UTF-8
        host: smtp.gmail.com
        username: ${mail}
        password: ${password}
        port: 587
        protocol: smtp
        test-connection: false
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                debug: true

secret:
    token: test
